# shell command
alias rmi='rm -i'
alias mvi='mv -i'
alias cpi='cp -i'
alias grep='grep --color -n'
alias ll='ls -lh'
alias lf='ls -F'
alias lm='ls -al | more'
alias eecho='echo -e'
alias tmux='tmux -2'

# programs
alias sb='subl . &'
alias pg='ping www.google.com'
alias ev='evince'
alias xo='xdg-open'
alias xoo='xdg-open .'
alias bp='bpython'
alias pc='pcmanfm'
alias df='df -Th'
alias py='python'
alias matlabnd='matlab -nodesktop -nosplash'
alias sup='sudo apt-get update'
alias sug='sudo apt-get upgrade'
alias dstat='dstat -cdlmnpsy'
alias vg='valgrind'
alias py='python'
alias qt='qtcreator &'
alias ec='bash -i -c "eclipse"'
alias acl='sudo apt-get autoclean'
alias arm='sudo apt-get autoremove'

# git
alias g='git'
alias groot='cd "$(git rev-parse --show-toplevel)"'
alias gst='git status'
alias gba='git branch -a'

# ssh
alias eniac='ssh -X quchao@eniac.seas.upenn.edu'
alias meam620='ssh -X meam620@eniac.seas.upenn.edu'
alias biglab='ssh -X quchao@biglab.seas.upenn.edu'
alias rdesk='rdesktop vlab-rdp.seas.upenn.edu'

# source bashrc
alias sbrc='source ~/.bashrc'
alias scat='source devel/setup.bash'

# fasd
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias sa='fasd -sia'
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias v='f -e vim'       # quick opening files with vim
alias vv='sf -e vim'     # quick opening files with vim interactively
alias m='f -e mplayer'   # quick opening files with mplayer
alias o='a -e xdg-open'  # quick opening files with xdg-open
alias oo='sa -e xdg-open' # quick opening files with xdg-open interactively
alias p='f -e evince'    # quick opening pdf files with evince

#cd
alias cd..='cd ..'
alias cd...='cd ../..'
alias cd....='cd ../../..'
alias cd.....='cd ../../../..'
alias cd......='cd ../../../../..'
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

#ros
alias rqtrc='rosrun rqt_reconfigure rqt_reconfigure'
alias rqtrt='rosrun rqt_runtime_monitor rqt_runtime_monitor'
alias rqtiv='rqt_image_view'
alias rosl='roslaunch'
alias rost='rostopic'
alias rosm='rosmsg'
alias rosr='rosrun'
alias rosp='rospack'
alias rosm='rosmake'
alias rosenv='env | grep ROS'
alias rmdb='rm -rf build devel'
alias cmk='catkin_make'
alias rmk='remake'
alias mk='make'

#ssh
alias atria='ssh galt@192.168.129.103'
alias antares='ssh antares@192.168.129.104'
alias xu-galt='ssh odroid@192.168.129.120'
