alias rmi="rm -i"
alias mvi="mv -i"
alias cpi="cp -i"
alias grep="grep --color -n"
alias ll="ls -lh"
alias ev="evince"
alias xo="xdg-open"
alias bp="bpython"
alias pc="pcmanfm"
alias df="df -Th"
alias matlabnd="matlab -nodesktop -nosplash"
alias eniac="ssh -X quchao@eniac.seas.upenn.edu"
alias biglab="ssh -X quchao@biglab.seas.upenn.edu"
alias mrsl="ssh -X chao@192.168.129.221"
alias rdesk="rdesktop vlab-rdp.seas.upenn.edu"
alias sbrc="source ~/.bashrc"
alias vbrc="vim ~/.bashrc"
#cd
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd......="cd ../../../../.."
#nanoplus
alias nanoplus20="ssh root@192.168.129.77"
alias nanoplus21="ssh root@192.168.129.78"
alias uri_nanoplus='export ROS_MASTER_URI=http://192.168.129.77:11311;echo $ROS_MASTER_URI'
alias uri_local='export ROS_MASTER_URI=http://localhost:11311;echo $ROS_MASTER_URI'
alias ros_var="env | grep ROS_"
alias ros_hydro="source /opt/ros/hydro/setup.bash"
alias ros_groovy="source /opt/ros/groovy/setup.bash"
alias ros_path="ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/chao/Dropbox/Research/ros"
