alias rmi="rm -i"
alias mvi="mv -i"
alias cpi="cp -i"
alias grep="grep --color -n"
alias ll="ls -lh"
alias ev="evince"
alias xo="xdg-open"
alias bp="bpython"
alias pc="pcmanfm"
alias df="df -Th"
alias matlabnd="matlab -nodesktop -nosplash"
alias eniac="ssh -X quchao@eniac.seas.upenn.edu"
alias biglab="ssh -X quchao@biglab.seas.upenn.edu"
alias mrsl="ssh -X chao@192.168.129.221"
alias rdesk="rdesktop vlab-rdp.seas.upenn.edu"
#cd
alias cd..="cd .."
alias cd...="cd ../.."
alias cd....="cd ../../.."
alias cd.....="cd ../../../.."
alias cd......="cd ../../../../.."
#nanoplus
alias nanoplus20="ssh root@192.168.129.77"
alias uri_nanoplus="export ROS_MASTER_URI=http://192.168.129.77:11311; env | grep ROS_MASTER_URI"
alias uri_local="export ROS_MASTER_URI=http://localhost:11311; env | grep ROS_MASTER_URI"
alias ros_var="env | grep ROS_"
alias ros_hydro="source /opt/ros/hydro/setup.bash; ros_var"
alias ros_groovy="source /opt/ros/groovy/setup.bash; ros_var"
alias ros_fuerte="source /opt/ros/fuerte/setup.bash; ros_var"
alias ros_nanoplus="uri_nanoplus; ros_groovy"
alias ros_trooper="source ~/trooper/setup.sh; uri_local; ros_var"
