alias rmi="rm -i"
alias mvi="mv -i"
alias cpi="cp -i"
alias grep="grep --color -n"
alias ll="ls -lh"
alias ev="evince"
alias xo="xdg-open"
alias df="df -Th"
alias matlabnd="matlab -nodesktop -nosplash"
alias eniac="ssh quchao@eniac.seas.upenn.edu"
alias biglab="ssh quchao@biglab.seas.upenn.edu"

