#!/usr/bin/env python3
import click
import os
from pathlib import Path
import subprocess as sp


def build(build_dir, install):
    os.chdir(build_dir)
    sp.run(["cmake", ".."])
    sp.run(["make", "-j8"])
    if install:
        sp.run(["sudo", "make", "install"])


@click.command()
@click.option('--install/--no-install', default=True)
def main(install):
    cwd = Path.cwd()
    print(cwd)

    for pkg in cwd.iterdir():
        if not pkg.is_dir():
            continue

        print(pkg)
        os.chdir(pkg)

        build_dir = pkg / "build"
        if not build_dir.exists():
            continue

        build(build_dir, install)


if __name__ == '__main__':
    main()