#!/usr/bin/env python3
import os
from pathlib import Path
from loguru import logger as L
import subprocess as sp

cwd = Path.cwd()
L.info(cwd)

for pkg in cwd.iterdir():
    if not pkg.is_dir():
        continue

    L.info(pkg)
    os.chdir(pkg)

    build_dir = pkg / "build"
    if not build_dir.exists():
        continue

    os.chdir(build_dir)
    sp.run(["cmake", ".."])
    sp.run(["make", "-j8"])
    sp.run(["sudo", "make", "install"])

